### ISSUE TITLE
Install Trimmomatic

### ISSUE THREAD

**Issue by LucyHut** [mdibl/package_downloads#31]
Create an automation that fetches and install new releases

**Comment by LucyHut** [comment]
Waiting for Joel to decide which source to use for updates - there were too many sources for this tool

**Comment by jhgraber** [comment]
Let's go with the java binary available at the main site:  
http://www.usadellab.org/cms/uploads/supplementary/Trimmomatic/Trimmomatic-0.36.zip
http://www.usadellab.org/cms/?page=trimmomatic

It seems to be the most up to date.

Probably also worth getting the manual
http://www.usadellab.org/cms/uploads/supplementary/Trimmomatic/TrimmomaticManual_V0.32.pdf

**Comment by LucyHut** [comment]
Done
